# wandb sweep
program: scripts/mlp_synthetic.py
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  model.lr:
    min: 0.0001
    max: 0.01
  model.head_layers:
    value: 2
  model.head_hidden_dim:
    value: 1024
  model.hidden_dropout_prob:
    value: 0.1
  data.batch_size:
    value: 64
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/risk/mlp_synthetic.yaml"
  - "--data.wandb_artifact"
  - "cardiors/diffsurv/pysurv_square_0.3.pt:v4"
  - ${args}
project: diffsurv
entity: cardiors
