# wandb sweep
program: scripts/mlp_synthetic.py
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  model.lr:
    min: 0.0001
    max: 0.01
  model.head_layers:
    min: 0
    max: 2
  model.head_hidden_dim:
    min: 128
    max: 1024
  model.hidden_dropout_prob:
    min: 0.0
    max: 0.5
  data.batch_size:
    values: [16, 32, 64, 128]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/risk/mlp_synthetic.yaml"
  - "--data.path"
  - "/lustre/home/rmhivau/ehrgnn/data/synthetic/pysurv_gaussian_weibull_0.3.pt"
  - ${args}
project: ehrgnn
