# wandb sweep
program: scripts/mlpdiffsort_synthetic.py
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  model.ignore_censoring:
    value: True
  model.lr:
    value: 0.003
  model.head_layers:
    value: 1
  model.head_hidden_dim:
    value: 1000
  model.hidden_dropout_prob:
    value: 0.1
  model.steepness:
    min: 10
    max: 50
  model.art_lambda:
    value: 0.0 # doesn't matter for cauchy
  model.distribution:
    value: cauchy
  model.sorting_network:
    value: bitonic
  data.batch_size:
    value: 32
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/risk/mlpdiffsort_synthetic.yaml"
  - "--data.path"
  - "/home/rmhivau/diffsurv/data/synthetic/pysurv_square_0.1.pt"
  - ${args}
project: ehrgnn
