# wandb sweep
program: scripts/mlpdiffsort_synthetic.py
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  model.lr:
    value: 0.003
  model.head_layers:
    value: 1
  model.head_hidden_dim:
    value: 128
  model.hidden_dropout_prob:
    value: 0.1
  model.steepness:
    min: 10
    max: 50
  model.art_lambda:
    value: 0.0 # doesn't matter for cauchy
  model.distribution:
    value: cauchy
  data.batch_size:
    value: 64
command:
  - ${env}
  - ${interpreter}
  - ${program}s
  - fit
  - "--config"
  - "jobs/configs/risk/mlpdiffsort_synthetic.yaml"
  - "--data.path"
  - "/lustre/home/rmhivau/ehrgnn/data/synthetic/pysurv_square_0.3.pt"
  - ${args}
project: ehrgnn
