data:
  token_col: concept_id
  label_col: phecode
  train_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_train.feather
  val_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_val.feather
  test_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_test.feather
  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/concept_vocab_14719.pkl
  #  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/code_vocab_43253.pkl
  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phecode_vocab_1564.pkl
  age_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/age_vocab_90.pkl
  weightings_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/weightings.pkl
  drop_unk: True
