
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/tensorboard/
        name: mlp


