data:
  #  token_col: concept_id
  token_col: phecode
  label_col: phecode
  train_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_train.feather
  val_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_val.feather
  test_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_test.feather
  #  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/concept_vocab_15003.pkl
  #  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phecode_vocab_3169.pkl
  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phecode_vocab_top_1003.pkl
  #  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phecode_vocab_3169.pkl
  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phecode_vocab_top_1003.pkl
#  weightings_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/weightings_x.pl
  incidence_grouping_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/incidence_groupings_x.pkl
  drop_unk: True

