data:
  token_col: concept_id
  label_col: phecode
  train_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_train.parquet
  val_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_val.parquet
  test_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phe_test.parquet
  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/concept_vocab_4809.pkl
  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/omop/phecode_vocab_695.pkl
trainer:
  logger:
    - class_path: src.models.loggers.CustomWandbLogger
      init_args:
        project: ehrgnn
        entity: qndre
        save_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/wandb/
        tags:
          - mlp
          - concept_id
          - risk
          - relu
          - omop
          - new_vocab
          - layernorm
        log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 30
        monitor: val/loss
        min_delta: 0.0
        mode: min
  max_epochs: 100
  check_val_every_n_epoch: 1
  val_check_interval: 0.2
  enable_checkpointing: True
  num_sanity_val_steps: 2
  accumulate_grad_batches: 8
  default_root_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/

