data:
  wandb_artifact: cardiors/diffsurv/flchain.pt:latest
  batch_size: "32, 8"
  num_workers: -1
model:
  lr: 0.0004051723506099132
  weight_decay: 0.00005338782262702786
  cph_method: ranked_list
