data:
  wandb_artifact: cardiors/diffsurv/nwtco.pt:latest
  batch_risk_tuple: "4, 64"
  num_workers: -1
model:
  lr: 0.009420405374745096
  weight_decay: 0.00004509547811024736
  cph_method: ranked_list
