trainer:
  logger:
    - class_path: models.loggers.CustomWandbLogger
      init_args:
        project: diffsurv
        entity: cardiors
        tags:
          - mlp
          - synthetic
          - risk
          - case-control-sampling
  max_epochs: 15
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  val_check_interval: 0.5
  enable_checkpointing: True
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  default_root_dir: .
  limit_val_batches: 0.0
#  precision: 16
data:
  wandb_artifact: cardiors/diffsurv/nwtco.pt:latest
  batch_risk_tuple: "4, 64"
  val_split: 0.0
  num_workers: -1
model:
  lr: 0.009420405374745096
  weight_decay: 0.00004509547811024736
  cph_method: ranked_list
  head_layers: 1
  embedding_dim: 5
  head_hidden_dim: 64
  only_covs: True
  cov_size: 3
  hidden_dropout_prob: 0.1
  batch_norm: True
seed_everything: 42
