data:
  wandb_artifact: cardiors/diffsurv/metabric.pt:latest
  batch_risk_tuple: "32, 8"
  num_workers: -1
model:
  lr: 0.006479995128858282
  weight_decay: 0.0038927824386519663
  cph_method: ranked_list
