trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: diffsurv
        entity: cardiors
        log_model: True
        tags:
          - mlp
          - risk
          - diffsort
          - case-control-sampling
  max_epochs: 15
  val_check_interval: 0.5
  log_every_n_steps: 10
  enable_checkpointing: True
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  limit_val_batches: 0.0
data:
  wandb_artifact: cardiors/diffsurv/flchain.pt:latest
  val_split: 0.0
  batch_risk_tuple: 32, 8
  num_workers: -1
model:
  lr: 0.004343696258007962
  weight_decay: 5.2546218078873754e-05
  only_covs: True
  head_layers: 1
  embedding_dim: 5
  head_hidden_dim: 64
  hidden_dropout_prob: 0.1
  sorting_network: bitonic
  batch_norm: True
  ignore_censoring: false
seed_everything: 42
