trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: diffsurv
        entity: cardiors
        log_model: True
        tags:
          - mlp
          - risk
          - diffsort
          - case-control-sampling
#        save_dir: /SAN/ihibiobank/denaxaslab/andre/diffsurv/results
#  callbacks:
#    - class_path: pytorch_lightning.callbacks.EarlyStopping
#      init_args:
#        patience: 10
#        monitor: val/c_index/all
#        min_delta: 0.000
#        mode: max
#        verbose: True
#        check_finite: False
#        check_on_train_epoch_end: True
  max_epochs: 15
#  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  enable_checkpointing: False
  num_sanity_val_steps: 0
  limit_val_batches: 0.0
  accumulate_grad_batches: 1
data:
  wandb_artifact: cardiors/diffsurv/support.pt:latest
  batch_risk_tuple: '16, 8'
  num_workers: 4
  val_split: 0.0
model:
  head_layers: 2
  embedding_dim: 5
  head_hidden_dim: 256
  lr: 0.0029582320154529357
  weight_decay: 0.000020837301147653676
  only_covs: True
  hidden_dropout_prob: 0.1
  sorting_network: bitonic
  distribution: cauchy
  ignore_censoring: true
