# wandb sweep
method: random
program: scripts/mlp.py
metric:
  name: hp_metric
  goal: maximize
parameters:
  model.batch_norm:
    value: True
  model.lr:
    value: 1e-3
  model.head_layers:
    values: 2
  model.head_hidden_dim:
    values: 128
  model.hidden_dropout_prob:
    value: 0.1
  data.batch_size:
    value: 32
  trainer.max_epochs:
    value: 50
  data.risk_set_size:
    values: [ 2, 4, 8, 16, 32, 64, 128]
  data.num_workers:
    value: -1
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlp.yaml"
  - "--data.wandb_artifact"
  - "cardiors/diffsurv/kkbox_v1:latest"
  - ${args}
project: diffsurv
entity: cardiors
