# wandb sweep
method: grid
program: scripts/mlpdiffsort.py
metric:
  name: hp_metric
  goal: maximize
parameters:
  data.return_perm_mat:
    value: True
  data.risk_set_size:
    values: [16, 32, 64, 128]
  model.lr:
    values:
      [0.03 , 0.01, 0.005]
  model.sorting_network:
    values:
      ["odd_even", "bitonic"]
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlpdiffsort_small.yaml"
  - "--data.wandb_artifact"
  - pysurv_linear_exp_nocensoring_ties10000_9.pt
#  - "/Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties10000_99.pt"
  - ${args}
project: diffsurv
entity: anon
