# wandb sweep
name: kkbox_mlp
method: random
program: scripts/mlp.py
metric:
  name: hp_metric
  goal: maximize
parameters:
  model.batch_norm:
    value: False
  model.lr:
    distribution: log_uniform_values
    min: 1e-4 # 0.0001
    max: 3e-2
  model.head_layers:
    value: 2
  model.head_hidden_dim:
    value: 128
  model.hidden_dropout_prob:
    value: 0.2
  data.batch_size:
    values: [32, 64, 84, 128]
  trainer.max_epochs:
    value: 50
  data.risk_set_size:
    values: [ 2, 4, 8, 16, 32, 64, 128]
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlp_kkbox.yaml"
  - "--data.wandb_artifact"
  - "anon/diffsurv/kkbox_v1:latest"
  - ${args}
project: diffsurv
entity: anon
