command:
  - ${env}
  - python3
  - ${program}
  - fit
  - --config
  - jobs/configs/risk/mlpdiffsort_small.yaml
  - ${args}
entity: cardiors
method: grid
metric:
  goal: maximize
  name: hp_metric
parameters:
  data.return_perm_mat:
    value: true
  data.risk_set_size:
    values:
      - 16
      - 32
      - 64
      - 128
  data.wandb_artifact:
    values:
      - pysurv27_linear_exp_independent_ties5_0.pt:latest
      - pysurv27_linear_exp_independent_ties10_0.pt:latest
      - pysurv27_linear_exp_independent_ties25_0.pt:latest
      - pysurv27_linear_exp_independent_ties50_0.pt:latest
      - pysurv27_linear_exp_independent_ties100_0.pt:latest
      - pysurv27_linear_exp_independent_ties2500_0.pt:latest
      - pysurv27_linear_exp_independent_ties10000_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties5_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties10_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties25_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties50_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties100_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties2500_0.pt:latest
      - pysurv27_linear_exp_nocensoring_ties10000_0.pt:latest
  model.lr:
    value: 0.01
  model.norm_risk:
    value: false
  model.optimizer:
    value: sgd
  model.sorting_network:
    values: [bitonic, odd_even]
  model.steepness:
    values:
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
      - 24
      - 26
      - 28
      - 30
      - 32
      - 34
      - 36
      - 38
      - 40
      - 42
      - 44
      - 46
      - 48
      - 50
program: scripts/mlpdiffsort.py
project: diffsurv
