trainer:
  logger:
    - class_path: src.models.loggers.CustomWandbLogger
      init_args:
        project: diffsurv
        entity: qndre
        save_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/wandb/
        tags:
          - mlp
          - concept_id
          - risk
        log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 30
        monitor: val/loss
        min_delta: 0.0
        mode: min
  max_epochs: 100
  check_val_every_n_epoch: 1
  val_check_interval: 0.2
  enable_checkpointing: True
  num_sanity_val_steps: 2
  accumulate_grad_batches: 4
  default_root_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/
data:
  debug: True
  token_col: concept_id
  label_col: phecode
  train_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_train.parquet
  val_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_val.parquet
  test_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_test.parquet
  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/concept_vocab_1472.pkl
  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phecode_vocab_1096.pkl
  batch_size: 64
  num_workers: 8
model:
  input_dim: 4697
  output_dim: 794
  count: False