trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: diffsurv
        entity: cardiors
        log_model: True
        tags:
          - mlp
          - risk
          - diffsort
          - case-control-sampling
        save_dir: /SAN/ihibiobank/denaxaslab/andre/diffsurv/results
  max_epochs: 5
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  val_check_interval: 4
  limit_train_batches: 200
  enable_checkpointing: False
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
#  default_root_dir: /home/rmhivau/diffsurv/wandb/
#  precision: 16
data:
#  local_path: "/Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties9000_nocensoring.pt"
#  local_path: /Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties9000_33.pt
#  local_path: /Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties_10000_nocensoring.pt
#  local_path: "/Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties_10000_nocensoring_unif.pt"
#  local_path: "/Users/andre/Documents/UCL/diffsurv/data/synthetic/pysurv_linear_exp_independent_ties_5_0.3_unif.pt"
#  wandb_artifact: pysurv_linear_exp_nocensoring_ties5_9.pt:latest
  wandb_artifact: pysurv_linear_exp_independent_ties1000_9.pt:latest
  batch_size: 64
  risk_set_size: 32
  num_workers: 0
model:
  head_layers: 0
  lr: 0.03 # from auto lr find
  only_covs: True
  hidden_dropout_prob: 0
  sorting_network: bitonic
  steepness: 15.1
  optimizer: sgd
  batch_norm: False
  norm_risk: True
#  sorter_size: 10 # must be controls per case + 1 if not None else batch_size
#  distribution: logistic
  distribution: cauchy
  ignore_censoring: True
#  pretrained_embedding_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/embeddings/graph_full_211122_prone_32_edge_weights_2021-12-13_in_gnn.pt
#  embedding_dim: 32
#ckpt_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/diffsurv/wwtgf7oi/checkpoints/epoch=3-step=3878.ckpt
