trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: diffsurv
        entity: cardiors
        tags:
          - mlp
          - synthetic
          - risk
          - diffsort
        save_dir: /SAN/ihibiobank/denaxaslab/andre/diffsurv/results
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 50
        monitor: hp_metric
        min_delta: 0.002
        mode: max
        verbose: True
        check_finite: False
    #    - class_path: src.callbacks.LogPredictionsCallback
    #    - class_path: callbacks.OnTrainEndResults
    #  init_args:
    #    save_dir: "mlpdiffsort_synthetic"
  max_epochs: 20
  check_val_every_n_epoch: 1
  val_check_interval: 10
  log_every_n_steps: 1
  enable_checkpointing: False
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
#  default_root_dir: /home/rmhivau/diffsurv/wandb/
#  precision: 16
data:
  #  path: /lustre/home/rmhivau/diffsurv/data/synthetic/nonlinear_exp_synthetic_no_censoring.pt
  #  local_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/synthetic/pysurv_square_0.1.pt
#  wandb_artifact: cardiors/diffsurv/rr_nl_nhp.pt:latest
#  wandb_artifact: cardiors/diffsurv/pysurv_square_independent_0.3.pt:latest
  wandb_artifact: cardiors/diffsurv/kkbox_v1:latest
#  wandb_artifact: cardiors/diffsurv/pysurv_square_mean_0.3.pt:latest
  val_split: 0.2
  batch_size: 64
  risk_set_size: 10
  num_workers: 1
model:
  head_layers: 2
  embedding_dim: 5
  head_hidden_dim: 1024
  lr: 0.03 # from auto lr find
  only_covs: True
  hidden_dropout_prob: 0.1
  sorting_network: bitonic
  steepness: 19
#  sorter_size: 10 # must be controls per case + 1 if not None else batch_size
  art_lambda: 0.0
  use_buckets: True
  distribution: cauchy
  ignore_censoring: true

#  pretrained_embedding_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/embeddings/graph_full_211122_prone_32_edge_weights_2021-12-13_in_gnn.pt
#  embedding_dim: 32

#ckpt_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/diffsurv/wwtgf7oi/checkpoints/epoch=3-step=3878.ckpt
