trainer:
  #  logger:
  #    - class_path: src.models.loggers.CustomWandbLogger
  #      init_args:
  #        project: diffsurv
  #        entity: qndre
  #        save_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/wandb/
  #        tags:
  #          - bert
  #          - concept_id
  #          - risk
  #          - in_gnn
  #          - layernorm
  #        log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 10
        monitor: val/loss
        min_delta: 0.000001
        mode: min
  max_epochs: 100
  check_val_every_n_epoch: 1
  val_check_interval: 0.5
  enable_checkpointing: True
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1
  default_root_dir: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/
data:
  debug: False
  token_col: concept_id
  label_col: phecode
  train_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_train.feather
  val_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_val.feather
  test_data_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phe_test.feather
  token_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/concept_vocab_14719.pkl
  label_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/phecode_vocab_1564.pkl
  age_vocab_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/age_vocab_90.pkl
  weightings_path: /SAN/ihibiobank/denaxaslab/andre/UKBB/data/processed/in_gnn/weightings.pt
  batch_size: 300
  num_workers: 1
model:
  #  pretrained_embedding_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/embeddings/graph_full_211122_prone_32_edge_weights_2021-12-13.pt
  #  pretrained_embedding_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/embeddings/graph_full_211209_prone_256_edge_weights_no_shortcuts_2022-01-05.pt
  #  freeze_pretrained: False
  embedding_dim: 256
  num_attention_heads: 2
  num_hidden_layers: 3
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  intermediate_size: 512
  lr: 0.001 # from auto lr find
  use_weighted_loss: True
#  pretrained_embedding_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/embeddings/graph_full_211122_prone_32_edge_weights_2021-12-13_in_gnn.pt
#  embedding_dim: 32

#ckpt_path: /SAN/ihibiobank/denaxaslab/andre/ehrgraphs/models/checkpoints/diffsurv/wwtgf7oi/checkpoints/epoch=3-step=3878.ckpt
