# wandb sweep
name: conv_cxr
program: scripts/conv_cxr.py
method: grid
metric:
  name: val/c_index/all
  goal: maximize
parameters:
  data.batch_risk_tuple:
    values: ['1, 128', '4, 32', '16, 8', '64, 2']
  seed_everything:
#    value: 42
    values: [1,2,3,4,5]  # will act as trails
  model.weight_decay:
    value: 0.00001
  model.lr:
    value: 0.0001
  data.num_workers:
    value: -1
  model.cph_method:
    value: ranked_list
  trainer.strategy:
    value: ddp
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/conv_cxr.yml"
  - ${args}
project: diffsurv
entity: cardiors
