# wandb sweep
name: conv_svhn_c0.3_bucket_beta
program: scripts/conv.py
method: grid
metric:
  name: val/c_index/all
  goal: maximize
parameters:
#  data.risk_set_size:
#    values: [2,4,8,16,32]
#  data.batch_size:
#    value: 100
  data.batch_risk_tuple:
#    values: ['8, 128', '32, 32', '128, 8', '512, 2']
#    value: '128, 8'
    value: '32, 32'
  seed_everything:
#    values: [1,2,3,4,5]  # will act as trails
    values: [1,2,3] # will act as trails
  model.cph_method:
    values: [ranked_list, breslow, efron]
  model.weight_decay:
    value: 0.00001
  model.lr:
    value: 0.0001
#    values: [1.00000000e-01, 1.00000000e-02]
  data.num_workers:
    value: -1
  trainer.strategy:
    value: ddp_find_unused_parameters_false
  data.wandb_artifact:
    values:
      [
        'cardiors/diffsurv/SVHN_buckets0_beta1_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets2_beta1_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets10_beta1_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets100_beta1_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets0_beta100_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets2_beta100_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets10_beta100_cen0.3_reverse:latest',
        'cardiors/diffsurv/SVHN_buckets100_beta100_cen0.3_reverse:latest',
      ]
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/conv.yml"
  - ${args}
project: diffsurv
entity: cardiors
