# wandb sweep
name: convdiffsort_cxr_topk
program: scripts/convdiffsort_cxr.py
method: grid
metric:
  name: val/topk
  goal: maximize
parameters:
  data.batch_risk_tuple:
    values: ['1, 128', '4, 32']
  seed_everything:
    values: [1,2,3,4,5]  # will act as trails
  model.weight_decay:
    value: 0.00001
  model.lr:
    value: 0.0001
  model.sorting_network:
    values: [bitonic, odd_even]
  data.num_workers:
    value: -1
  trainer.strategy:
    value: ddp_find_unused_parameters_false
  model.optimize_combined:
    value: False
  model.optimize_topk:
    value: True
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/convdiffsort_cxr.yml"
  - ${args}
project: diffsurv
entity: cardiors
