name: ehrgnn
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - conda
  - python=3.8
  - ipython
  - pytorch=1.11=py3.8_cuda11.5_cudnn8.3.2_0
  - numpy
  - torchmetrics
  - pyg
  - pytorch-lightning=1.6.3
  - wandb
  - python-dotenv
  - dill
  - numba
