name: ehrgnn
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - conda
  - python=3.8
  - ipython
  - pymongo
  - torchmetrics
  - torchvision
  - pytorch=1.11
  - pycairo
  - pygobject
  - notebook
  - tensorboard
  - hyperopt
  - gh
  - jsonargparse
  - pandas
  - torchaudio
  - pytorch-lightning=1.5.9
  - docstring_parser
  - wandb
  - pip
  - pyg
  - pytorch-lightning=1.6.3
  - wandb
  - python-dotenv
  - dill
  - numba
  - pandas
  - pysurvival
  - pillow

